import type { Metadata } from "next";
import { Geist, Geist_Mono, Barlow_Condensed, Barlow } from "next/font/google";
import "./globals.css";

const bardlowCondensed = Barlow_Condensed({
  variable: "--font-bardlow-condensed",
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${barlow.variable} ${bardlowCondensed.variable}`}
    >
      <body className="antialiased bg-background text-foreground">
        <div className="h-8 bg-brand-dark"></div>
        <div className="h-20 bg-white px-8 py-1 flex items-center">
          <a href="/" className="mx-auto lg:mx-0 h-full">
            <img src="/anxiousloomers_main_logo.avif" className="h-full" />
          </a>
          <div className="hidden lg:flex mx-8 gap-8 text-[rgb(0,87,18)] justify-center">
            <a href="/">About Us</a>
            <a href="/">Partners</a>
            <a href="/">Programs</a>
            <a href="/">Resources</a>
            <a href="/">Shop</a>
            <a href="/">Contact</a>
            <a href="/">Legal Notice</a>
          </div>
        </div>
        {children}
        <div className="bg-brand-dark p-4 text-white text-center flex gap-4">
          <div>© 2026, ANXIOUSLOOMERS</div>
          <div>&middot;</div>
          <a className="underline">Privacy Policy</a>
        </div>
      </body>
    </html>
  );
}
